# BanBook configuration file

General:
  BanTime: 7 # in days
  BanMessage: "you are got banned!"

skull:
  name: §b{player}
  lore:
    - §eRight-Clicks §7to set the player
    - §7as hunted for the next 24 hours!

info-item:
  name: information Book!
  lore:
    - all the info
    - of what
    - you can do
    - in this window

previous-button:
  name: previous
  lore:
    - click on me
    - to go to
    - the previous page

next-button:
  name: next
  lore:
    - click on me
    - to go to
    - the next page

confirm-item:
  name: §b§lHunt Trigger for {player}
  lore:
    - §7§oClick to initiate the hunt.
    - §7§oThis will target the player {player}.
    - §7§oEnsure you're prepared before proceeding!
